### ISSUE TITLE
Suggestion: Remove background

### ISSUE THREAD

**Issue by Reds94** [d2armory/flare#7]
I used to use Dota Hattery to get nice transparent pictures of the heroes since the background on that site was completely black. Would you be able to add a toggle to turn the background on and off? Perhaps even make it so you could use a color wheel to change the color to a nice, chroma friendly green? Love the site by the way. I hope this was the right part of this site to do a suggestion.

**Comment by bongikairu** [comment]
Edit engine to allow pulling raw image

use this in frontend 

```
var y = window.open("about:blank"); y.document.write("<img src=\"" +canvas.toDataURL("image/png") + "\" />");
```

**Comment by wq9** [comment]
Clicking on Camera icon in top bar opens the image with transparency. What do we do about the size of the image?

**Comment by bongikairu** [comment]
It's in an img tag so we might be able to cap its size with css.
